name: create_spurte
description: Create a Spurte Application with no hassle and with your favourite tools
version: 0.0.1-pre
repository: https://github.com/nikeokoronkwo/spurte-dart

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cli_dialog: ^0.5.0
  cli_util: ^0.4.1
  io: ^1.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
